all:
	make -C commonutils
	make -C b3d2
	make -C coral
	make -C hydrobalance

install: 
	make -C commonutils install
	make -C b3d2 install
	make -C coral install
	make -C hydrobalance install

commonutils :
	make -C commonutils

b3d2 :
	make -C b3d2

coral :
	make -C coral

hydrobalance :
	make -C hydrobalance

uninstall :
	make -C commonutils uninstall
	make -C b3d2 uninstall
	make -C coral uninstall
	make -C hydrobalance uninstall

clean :
	make -C commonutils clean
	make -C b3d2 clean
	make -C coral clean
	make -C hydrobalance clean
	
	
